@startuml
scale 1024*2048
actor 利用者
control 変換依頼
control 画像を変換する
control 変換前の画像をアップロードする
control 変換後の画像をダウンロードする
boundary 入力画面
boundary 確認画面
entity 変換前の画像データ
entity 変換後の画像データ

(利用者) -right-> (入力画面)
(利用者) -down-> (確認画面)
(変換依頼)-right->(変換前の画像をアップロードする)
(変換前の画像をアップロードする)-down->(変換前の画像データ)
(画像を変換する)-down->(変換前の画像データ)
(画像を変換する)-down->(変換後の画像データ)
(変換後の画像をダウンロードする)-down->(変換後の画像データ)
(確認画面)-right->(変換後の画像をダウンロードする)
(入力画面) -down-> (変換依頼)
(変換依頼)->(画像を変換する)


@enduml